### ISSUE TITLE
Support for CF workers

### ISSUE THREAD

**Issue by piscesCat** [megahertz/twigjs-loader#18]
CF workers don't support FS, i.e. there isn't any way to read file content from the system. but I can use fetch or import. Is it useful?

**Comment by megahertz** [comment]
@piscesCat A compiled template doesn't require node.js runtime since it should work fine in a web browser. As for the plugin itself, it doesn't require fs too (but I'm not sure about twig.js). Anyway, the plugin expects to work with webpack which requires node.js runtime. Please let me know if I missed something and add more detail.

**Comment by piscesCat** [comment]
For CF, it stores data in KV, not FS. I want to customize the loader to get data from KV.

**Comment by megahertz** [comment]
Do you want to store a compiled template in KV or just data? A code example could be useful.

**Comment by piscesCat** [comment]
> be

 I want to save the template to KV, exactly the template name (file name) is KEY and the HTML/twig part is VALUE
I would expect {{ include('tpl name') }} to work

**Comment by piscesCat** [comment]
> Do you want to store a compiled template in KV or just data? A code example could be useful.

I want to save the template to KV, exactly the template name (file name) is KEY and the HTML/twig part is VALUE
I would expect {{ include('tpl name') }} to work

**Comment by megahertz** [comment]
That's not possible to `{{ include('tpl name') }}` since the compiled template is js code, not a twig template. But you can try to override `renderTemplate` option to export `twigData` (a compiled template AST) instead of returning a function. You can store this data in KV. In that case, you should pass this data to Twig.js by yourself.
