### ISSUE TITLE
Use client build file with Twig module

### ISSUE THREAD

**Issue by stephane-r** [megahertz/twigjs-loader#3]
Hello Alexey :)

Is it possible to load the client file for Twig module ?

In my case, i use Twig on client side app, but babel not transpile fat arrow `=>` because it load the server file.

You can see server and client build : https://github.com/twigjs/twig.js/blob/master/webpack.config.js

I would like use twig.min.js builded file with your loader, is it currently possible ?

Thank you :)

**Comment by megahertz** [comment]
Hi @stephane-r 

[Here's an example](https://github.com/megahertz/twigjs-loader/tree/master/examples/frontend) where twig templates are used on client side.

If I understand correctly, you want to load twig.min.js manually instead of include it to a bundle file.
In this case you can set a custom renderTemplate function which uses global Twig object instead of loading commonjs module, similar to:

```js
...
use:  {
  loader: 'twigjs-loader',
  options: {
    renderTemplate(twigData, dependencies, isHot) {
      return `
        ${dependencies}
        var tpl = Twig.twig(${JSON.stringify(twigData)});
        module.exports = function(context) { return tpl.render(context); };
      `;
    },
  },
},
...
```

Make sure twig.min.js is loaded before the bundle.

**Comment by stephane-r** [comment]
Hi @megahertz 

Mmm, i need to include `twig.min.js` on my webpack entries for working on client side ?

**Comment by megahertz** [comment]
@stephane-r No, if you just want to include twig.js, it's better to include it in the same bundle as your templates. In this case you can just copy a webpack config from the example project above.

**Comment by stephane-r** [comment]
Ok, thank you :)

On your example, i'm not really understand when you use twig.js or twig.min.js file. In IE11, your example don't work because webpack twig.js file (not transpiled by babel).

**Comment by megahertz** [comment]
It isn't required directly. twig.js is bundled as a dependency of a template. Just tested the example above and it works in IE 9 and newer. Does the example work for you in another browsers?

**Comment by megahertz** [comment]
Feel free to reopen if the issue is still relevant.
