### ISSUE TITLE
Namspaces support

### ISSUE THREAD

**Issue by Cronos87** [megahertz/twigjs-loader#8]
Hello!

Is it possible to customize the namespaces?

In your examples I only found relative path but nothing like: `@my-namespace/template.twig`.

Twig have support for this, see here: https://github.com/twigjs/twig.js/wiki#user-content-namespaces

Thank you in advance for the answer.

**Comment by megahertz** [comment]
Try to use webpack alias for the purpose.

**Comment by Cronos87** [comment]
Thank you for your answer.

But how to resolve this kind of template for example: `{% include 'macro::sprite.twig' %}` ?

Can you show me an example please?

Thanks.

**Comment by megahertz** [comment]
Sorry, I haven't experimented with the feature yet.

Try to define some alias in webpack config (resolve.alias) and then use it in your templates. Please let me know if there are some issues with that approach.

**Comment by henrijs** [comment]
@megahertz if you come around to tackle this, here is example code... https://github.com/zimmo-be/twig-loader/compare/master...henrijs:master from `twig-loader` that suffers from same issue.

**Comment by megahertz** [comment]
@henrijs Thank you. I'll try to play with it a bit later

**Comment by megahertz** [comment]
Namespace feature works out of box, I've added an example for that.

**Comment by YoungElPaso** [comment]
@megahertz i understand you can do this via webpack resolve, but the namespace/path option is a standard Twig option (like autoescape etc) and is supported by Twig JS. The solution @henrijs proposes fits with that, which is also pretty similar to how Twig options work in PHP.

I noticed Twig-loader also rejected similar PR/issue, but TBH I don't really get that either. Shouldn't namespaces be handled as closely to how Twig recommends even though this is coincidentally similar to a webpack feature? Asking more out of curiosity than anything.

**Comment by megahertz** [comment]
@YoungElPaso I would prefer a single way to do some action, especially in a case when alternative implementation makes code more complex and is less tested compared to the primary way. And, TBH, I see no reason why built-in namespace support could be better than resolving via webpack.

**Comment by YoungElPaso** [comment]
OK, that's fair enough - that's what I expected you might say. I guess its just one of those things one has to live with. Webpack certainly is more likely to be maintained/tested by more people as well and the resolve functions are more general use.

I asked primarily because if unit testing Twig templates with twig-testing-library, you have to use the Twig.js namespace features anyway and I was hoping eventually for parity between app and testing implementations and I don't want to/can't remove webpack (and so loaders) from the equation in my app. 

But it's all good. Thanks for the response and great work 👍
